version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "80:80"
      

  web:
    build: .
    command: rails s -p 80 -b '0.0.0.0'
    command: rails s -p 422 -b '0.0.0.0'
    volumes:
      - .:/app_name
    ports:
      - "80:80"
    links:
      - db